[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "maia-chess"
version = "0.1.0"
description = "Dummy pyproject for installing maia-chess as editable (local)."
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["."]
